development:
  adapter: postgresql
  encoding: unicode
  database: yml_converter_dev
  pool: 5
  username: schaerli
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: yml_converter_test
  pool: 5
  username: schaerli
  password:
